databases:
  - name: mattermost
    plan: starter
  - name: matrix
    plan: starter
  - name: keycloak
    plan: starter

services:
  - type: pserv
    name: mattermost-minio
    env: docker
    dockerfilePath: ./minio/Dockerfile
    dockerContext: ./minio
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: MINIO_ACCESS_KEY
        generateValue: true
      - key: MINIO_SECRET_KEY
        generateValue: true
  - type: web
    name: mattermost
    env: docker
    plan: starter
    dockerfilePath: ./mattermost/Dockerfile
    dockerContext: ./mattermost
    domains:
      - chat.cachednerds.com
    disk:
      name: config
      mountPath: /mattermost/config
      sizeGB: 1
    envVars:
      - key: MM_USERNAME
        fromDatabase:
          name: mattermost
          property: user
      - key: MM_PASSWORD
        fromDatabase:
          name: mattermost
          property: password
      - key: MM_DBNAME
        fromDatabase:
          name: mattermost
          property: database
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: mattermost
          property: host
      - key: MM_SERVICESETTINGS_LISTENADDRESS
        value: ":10000"
      - key: MM_FILESETTINGS_DRIVERNAME
        value: amazons3
      - key: MM_FILESETTINGS_AMAZONS3BUCKET
        value: mattermost
      - key: MM_FILESETTINGS_AMAZONS3ACCESSKEYID
        sync: false
      - key: MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY
        sync: false
      - key: MM_FILESETTINGS_AMAZONS3ENDPOINT
        fromService:
          type: pserv
          name: mattermost-minio
          property: hostport
      - key: MM_FILESETTINGS_AMAZONS3SSL
        value: "false"
#
# Matrix Server
#
  - type: web
    name: matrix
    env: docker
    plan: starter
    dockerfilePath: ./matrix/Dockerfile
    dockerContext: ./matrix
    domains:
      - matrix.cachednerds.com
    disk:
      name: config
      mountPath: /data
      sizeGB: 1
#
# Keycloak Server
#
  - type: web
    name: keycloak
    env: docker
    plan: standard
    repo: https://github.com/keycloak/keycloak-containers.git
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    domains:
      - keycloak.cachednerds.com
    envVars:
      - key: PROXY_ADDRESS_FORWARDING
        value: true
      - key: DB_VENDOR
        value: POSTGRES
      - key: DB_ADDR
        fromDatabase:
          name: keycloak
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: keycloak
          property: database
      - key: DB_SCHEMA
        value: public
      - key: DB_USER
        fromDatabase:
          name: keycloak
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: keycloak
          property: password
      - key: KEYCLOAK_PASSWORD
        generateValue: true
      - key: KEYCLOAK_USER
        generateValue: true
  #
  # Eliza Matrix Bot
  #
  - type: pserv
    name: elizabot
    env: docker
    dockerfilePath: ./eliza-bot/Dockerfile
    dockerContext: ./eliza-bot
    envVars:
      - key: ACCESS_TOKEN
        sync: false
      - key: MATRIX_SERVER_URI
        sync: false
